export const FETCH_APPROVALS = 'FETCH_APPROVALS';   
export const FETCH_APPROVALS_SUCCESS = 'FETCH_APPROVALS_SUCCESS';
export const FETCH_APPROVALS_FAILURE = 'FETCH_APPROVALS_FAILURE';
export const SUBMIT_FOR_APPROVAL = 'SUBMIT_FOR_APPROVAL';
export const SUBMIT_FOR_APPROVAL_SUCCESS = 'SUBMIT_FOR_APPROVAL_SUCCESS';
export const SUBMIT_FOR_APPROVAL_FAILURE = 'SUBMIT_FOR_APPROVAL_FAILURE';